// Resource management action types
export const CREATE_RESOURCE = "CREATE_RESOURCE";
export const GET_ALL_RESOURCES = "GET_ALL_RESOURCES";
export const GET_RESOURCES_FOR_USER = "GET_RESOURCES_FOR_USER";
export const SET_RESOURCE = "SET_RESOURCE";
export const GET_RESOURCE = "GET_RESOURCE";
export const GET_EDITOR_RESOURCES = "GET_EDITOR_RESOURCES";
export const UPDATE_RESOURCE = "UPDATE_RESOURCE";
export const DELETE_RESOURCE = "DELETE_RESOURCE";
export const CHANGE_RESOURCE_STATUS = "CHANGE_RESOURCE_STATUS";
export const RESOURCE_PAYMENT = "RESOURCE_PAYMENT";

// User account management types
export const CREATE_USER_ACCOUNT = "CREATE_USER_ACCOUNT";
export const GET_USER_ACCOUNT = "GET_USER_ACCOUNT";
export const SET_USER_ACCOUNT = "SET_USER_ACCOUNT";
export const UPDATE_USER_ACCOUNT = "UPDATE_USER_ACCOUNT";
export const DELETE_USER_ACCOUNT = "DELETE_USER_ACCOUNT";
export const GET_ALL_USER_ACCOUNTS = "GET_ALL_USER_ACCOUNTS";
export const GET_ALL_REVIEWER_ACCOUNTS = "GET_ALL_REVIEWER_ACCOUNTS";
export const GET_ALL_EDITOR_ACCOUNTS = "GET_ALL_EDITOR_ACCOUNTS";
export const GET_ALL_ADMIN_ACCOUNTS = "GET_ALL_ADMIN_ACCOUNTS";
export const LOGIN_USER_ACCOUNT = "LOGIN_USER_ACCOUNT";
export const GET_USER_NOTIFICATIONS = "GET_USER_NOTIFICATIONS";
export const CHANGE_USER_ROLE = "CHANGE_USER_ROLE";
export const REQUEST_CHANGE_USER_ROLE = "REQUEST_CHANGE_USER_ROLE";
export const GET_REQUEST_USER_ROLES = "GET_REQUEST_USER_ROLES";

// Conference management types
export const CREATE_CONFERENCE = "CREATE_CONFERENCE";
export const GET_CONFERENCE = "GET_CONFERENCE";
export const SET_CONFERENCE = "SET_CONFERENCE";
export const GET_ALL_CONFERENCES = "GET_ALL_CONFERENCES";
export const UPDATE_CONFERENCE = "UPDATE_CONFERENCE";
export const DELETE_CONFERENCE = "DELETE_CONFERENCE";
export const GET_CONFERENCES_FOR_ADMIN = "GET_CONFERENCES_FOR_ADMIN";
export const SET_CONFERENCE_STATUS = "SET_CONFERENCE_STATUS";

// Workshop management action types
export const CREATE_WORKSHOP = "CREATE_WORKSHOP";
export const GET_WORKSHOP = "GET_WORKSHOP";
export const SET_WORKSHOP = "SET_WORKSHOP";
export const UPDATE_WORKSHOP = "UPDATE_WORKSHOP";
export const DELETE_WORKSHOP = "DELETE_WORKSHOP";
export const GET_ALL_WORKSHOPS = "GET_ALL_WORKSHOPS";

// Payment management action typs
export const CHARGE_AMOUNT = "CHARGE_AMOUNT";
export const CHARGE_RESOURCE_AMOUNT = "CHARGE_RESOURCE_AMOUNT";
export const GET_PAYMENTS = "GET_PAYMENTS";
