// Resource management action types
export const CREATE_RESOURCE = "CREATE_RESOURCE";
export const GET_ALL_RESOURCES = "GET_ALL_RESOURCES";
export const SET_RESOURCE = "SET_RESOURCE";
export const GET_RESOURCE = "GET_RESOURCE";
export const GET_EDITOR_RESOURCES = "GET_EDITOR_RESOURCES";
export const UPDATE_RESOURCE = "UPDATE_RESOURCE";
export const DELETE_RESOURCE = "DELETE_RESOURCE";
export const CHANGE_RESOURCE_STATUS = "CHANGE_RESOURCE_STATUS";
export const RESOURCE_PAYMENT = "RESOURCE_PAYMENT";

// User account management types
export const CREATE_USER_ACCOUNT = "CREATE_USER_ACCOUNT";
export const GET_USER_ACCOUNT = "GET_USER_ACCOUNT";
export const SET_USER_ACCOUNT = "SET_USER_ACCOUNT";
export const UPDATE_USER_ACCOUNT = "UPDATE_USER_ACCOUNT";
export const DELETE_USER_ACCOUNT = "DELETE_USER_ACCOUNT";
export const GET_ALL_USER_ACCOUNTS = "GET_ALL_USER_ACCOUNTS";
export const GET_ALL_REVIEWER_ACCOUNTS = "GET_ALL_REVIEWER_ACCOUNTS";
export const GET_ALL_EDITOR_ACCOUNTS = "GET_ALL_EDITOR_ACCOUNTS";
export const GET_ALL_ADMIN_ACCOUNTS = "GET_ALL_ADMIN_ACCOUNTS";
export const LOGIN_USER_ACCOUNT = "LOGIN_USER_ACCOUNT";

// Conference management types
export const CREATE_CONFERENCE = "CREATE_CONFERENCE";
export const GET_CONFERENCE = "GET_CONFERENCE";
export const SET_CONFERENCE = "SET_CONFERENCE";
export const GET_ALL_CONFERENCES = "GET_ALL_CONFERENCES";
export const UPDATE_CONFERENCE = "UPDATE_CONFERENCE";
export const DELETE_CONFERENCE = "DELETE_CONFERENCE";
export const GET_CONFERENCES_FOR_ADMIN = "GET_CONFERENCES_FOR_ADMIN";
export const SET_CONFERENCE_STATUS = "SET_CONFERENCE_STATUS";